version: "3.8"

services:
  aio_bash_im:
    build: .
    container_name: aio_bash_im
    restart: unless-stopped
    labels:
      - "org.label-schema.group=apps"
      - "traefik.enable=true"
      - "traefik.http.routers.aiobashim.entrypoints=http"
      - "traefik.http.routers.aiobashim.rule=Host(`aiobashim.lionzxy.ru`)"
      - "traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.aiobashim.middlewares=portainer-https-redirect"
      - "traefik.http.routers.aiobashim-secure.entrypoints=https"
      - "traefik.http.routers.aiobashim-secure.rule=Host(`aiobashim.lionzxy.ru`)"
      - "traefik.http.routers.aiobashim-secure.tls=true"
      - "traefik.http.routers.aiobashim-secure.tls.certresolver=http"
      - "traefik.http.routers.aiobashim-secure.service=aiobashim"
      - "traefik.http.services.aiobashim.loadbalancer.server.port=8080"
      - "traefik.docker.network=traefik-proxy"